name: Renovate Bot

on:
  pull_request:
    branches:
      - test  # Запускать при PR в ветку test
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RENOVATE_CONFIG: >  # Указываем конфигурацию напрямую
            {
              "platform": "github",
              "repositories": ["nadyakarandasheva/ui-library"],
              "hostRules": [
                {
                  "hostType": "npm",
                  "matchHost": "npm.pkg.github.com",
                  "token": "${{ secrets.NPM_TOKEN }}"
                }
              ],
              "enabledManagers": ["npm"],
              "packageRules": [
                {
                  "matchPackageNames": ["@nadyakarandasheva/ui-library"],
                  "enabled": true,
                  "groupName": "UI Library Updates"
                }
              ]
            }
